spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      username: admin
#      password: 123456
#      database: testSpring
#      authentication-database: admin
      uri: mongodb://admin:123456@localhost:27017/testSpring

